// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphapi

import (
	"github.com/datumforge/geodetic/internal/ent/generated"
)

// Return response for createDatabase mutation
type DatabaseCreatePayload struct {
	// Created database
	Database *generated.Database `json:"database"`
}

// Return response for deleteDatabase mutation
type DatabaseDeletePayload struct {
	// Deleted database ID
	DeletedID string `json:"deletedID"`
}

// Return response for updateDatabase mutation
type DatabaseUpdatePayload struct {
	// Updated database
	Database *generated.Database `json:"database"`
}
