version: "3"

tasks:
  build:
    dir: ..
    desc: builds the geodetic docker image
    cmds:
      - "docker build -f docker/Dockerfile . -t geodetic:dev"

  geodetic:
    dir: ..
    desc: brings up the compose environment for the geodetic server configured with auth
    deps: [build]
    cmds:
      - "docker compose -f ./docker/docker-compose-redis.yml  -f ./docker/docker-compose.yml -f ./docker/docker-compose-fga.yml -p geodetic up -d"

  geodetic:down:
    dir: ..
    desc: brings the geodetic compose environment down
    cmds:
      - "docker compose -p geodetic down"

  postgres:
    dir: ..
    desc: brings up the compose environment for postgres development
    cmds:
      - "docker compose -f ./docker/docker-compose-pg.yml -p postgres up -d"

  postgres:down:
    dir: ..
    desc: brings the postgres compose environment down
    cmds:
      - docker compose -p postgres down

  all:up:
    dir: ..
    desc: brings up the full docker compose development environment including geodetic server, postgres, fga, and rover
    cmds:
      - task: geodetic
      - task: :rover

  all:down:
    dir: ..
    desc: brings down both fga and geodetic server compose environments
    cmds:
      - task: geodetic:down

  redis:
    dir: ..
    desc: brings up the compose environment for redis
    cmds:
      - "docker compose -f ./docker/docker-compose-redis.yml -p redis up -d"

  redis:down:
    dir: ..
    desc: brings up the compose environment for redis
    cmds:
      - "docker compose -p redis down"

  fga:
    dir: ..
    desc: brings up the compose environment for openfga development
    cmds:
      - "docker compose -f ./docker/docker-compose-fga.yml -p fga up -d"

  fga:down:
    dir: ..
    desc: brings the fga compose environment down
    cmds:
      - docker compose -p fga down

  fga:open:
    dir: ..
    desc: opens the fga playground in a browser
    cmds:
      - 'open "http://localhost:3000/playground"'

  fga:up:
    dir: ..
    desc: brings the fga compose environment up and opens the fga playground
    aliases: [fgaup]
    cmds:
      - task: fga
      - task: fga:open
